package unidesk.com.br.keymanager.ui.localization

import androidx.compose.runtime.*

// Manual string maps for each language
private val englishStrings = mapOf(
    "app_title" to "KeyManager",
    "nav_create_keystore" to "Create Keystore",
    "nav_open_keystore" to "Open Keystore",
    "nav_bulk_move" to "Bulk Key Move",
    "nav_settings" to "Settings",
    "settings_title" to "Settings",
    "settings_dark_mode" to "Dark Mode",
    "settings_dark_mode_desc" to "Use dark color scheme",
    "settings_keystore_format" to "Default Keystore Format",
    "settings_keystore_format_desc" to "Used when creating new keystores",
    "settings_auto_lock" to "Auto-lock Timeout",
    "settings_auto_lock_desc" to "Lock keystores after inactivity",
    "settings_language" to "Language",
    "settings_language_desc" to "Select UI language",
    "settings_close" to "Close",
    "timeout_never" to "Never",
    "timeout_5min" to "5 minutes",
    "timeout_10min" to "10 minutes",
    "timeout_15min" to "15 minutes",
    "timeout_30min" to "30 minutes",
    "timeout_1hour" to "1 hour",
    "lang_english" to "English",
    "lang_portuguese" to "Português (Brasil)",
    "search_keys" to "Search keys...",
    "search_keystores" to "Search keystores...",
    "action_sort" to "Sort",
    "sort_recent" to "Recent",
    "sort_name" to "Name",
    "sort_path" to "Path",
    "filter_all" to "All",
    "filter_private_keys" to "Private Keys",
    "filter_trusted_certs" to "Trusted Certs",
    "filter_secret_keys" to "Secret Keys",
    "action_filter" to "Filter",
    "action_refresh" to "Refresh",
    "empty_no_keystores" to "No keystores open",
    "empty_no_keystores_desc" to "Open or create a keystore to get started",
    "empty_no_keys" to "No keys in keystore",
    "empty_no_keys_desc" to "Create a new key or import certificates",
    "empty_keystore_locked" to "Keystore locked",
    "empty_keystore_locked_desc" to "Enter the password to unlock",
    "empty_no_selection" to "No keystore selected",
    "empty_no_selection_desc" to "Select a keystore from the list to view its contents",
    "empty_no_results" to "No keys found",
    "empty_no_results_desc" to "Try adjusting your search or filter",
    "validity_valid" to "Valid",
    "validity_expiring" to "Expiring",
    "validity_expired" to "Expired",
    "validity_unknown" to "Unknown",
    "action_unlock" to "Unlock",
    "action_close_keystore" to "Close keystore",
    "action_create_key" to "Create key",
    "action_change_password" to "Change password",
    "action_lock_keystore" to "Lock keystore",
    "action_view_details" to "View details",
    "action_export_cert" to "Export certificate",
    "action_rename" to "Rename",
    "action_move" to "Move",
    "action_delete" to "Delete",
    "entry_type_private_key" to "Private Key",
    "entry_type_trusted_cert" to "Trusted Cert",
    "entry_type_secret_key" to "Secret Key",
    "entry_type_unknown" to "Unknown",
    "valid_until" to "Valid until: %1\$s",
    "entries_count" to "entries",
    "table_header_recent" to "Recent",
    "table_header_open" to "Open"
)

private val portugueseStrings = mapOf(
    "app_title" to "KeyManager",
    "nav_create_keystore" to "Criar Keystore",
    "nav_open_keystore" to "Abrir Keystore",
    "nav_bulk_move" to "Mover Chaves em Lote",
    "nav_settings" to "Configurações",
    "settings_title" to "Configurações",
    "settings_dark_mode" to "Modo Escuro",
    "settings_dark_mode_desc" to "Usar esquema de cores escuro",
    "settings_keystore_format" to "Formato de Keystore Padrão",
    "settings_keystore_format_desc" to "Usado ao criar novas keystores",
    "settings_auto_lock" to "Tempo de Bloqueio Automático",
    "settings_auto_lock_desc" to "Bloquear keystores após inatividade",
    "settings_language" to "Idioma",
    "settings_language_desc" to "Selecionar idioma da interface",
    "settings_close" to "Fechar",
    "timeout_never" to "Nunca",
    "timeout_5min" to "5 minutos",
    "timeout_10min" to "10 minutos",
    "timeout_15min" to "15 minutos",
    "timeout_30min" to "30 minutos",
    "timeout_1hour" to "1 hora",
    "lang_english" to "English",
    "lang_portuguese" to "Português (Brasil)",
    "search_keys" to "Pesquisar chaves...",
    "search_keystores" to "Pesquisar keystores...",
    "action_sort" to "Ordenar",
    "sort_recent" to "Recente",
    "sort_name" to "Nome",
    "sort_path" to "Caminho",
    "filter_all" to "Todos",
    "filter_private_keys" to "Chaves Privadas",
    "filter_trusted_certs" to "Certificados Confiáveis",
    "filter_secret_keys" to "Chaves Secretas",
    "action_filter" to "Filtro",
    "action_refresh" to "Atualizar",
    "empty_no_keystores" to "Nenhuma keystore aberta",
    "empty_no_keystores_desc" to "Abra ou crie uma keystore para começar",
    "empty_no_keys" to "Nenhuma chave na keystore",
    "empty_no_keys_desc" to "Crie uma nova chave ou importe certificados",
    "empty_keystore_locked" to "Keystore bloqueada",
    "empty_keystore_locked_desc" to "Digite a senha para desbloquear",
    "empty_no_selection" to "Nenhuma keystore selecionada",
    "empty_no_selection_desc" to "Selecione uma keystore da lista para ver seu conteúdo",
    "empty_no_results" to "Nenhuma chave encontrada",
    "empty_no_results_desc" to "Tente ajustar sua pesquisa ou filtro",
    "validity_valid" to "Válido",
    "validity_expiring" to "Expirando",
    "validity_expired" to "Expirado",
    "validity_unknown" to "Desconhecido",
    "action_unlock" to "Desbloquear",
    "action_close_keystore" to "Fechar keystore",
    "action_create_key" to "Criar chave",
    "action_change_password" to "Alterar senha",
    "action_lock_keystore" to "Bloquear keystore",
    "action_view_details" to "Ver detalhes",
    "action_export_cert" to "Exportar certificado",
    "action_rename" to "Renomear",
    "action_move" to "Mover",
    "action_delete" to "Excluir",
    "entry_type_private_key" to "Chave Privada",
    "entry_type_trusted_cert" to "Certificado Confiável",
    "entry_type_secret_key" to "Chave Secreta",
    "entry_type_unknown" to "Desconhecido",
    "valid_until" to "Válido até: %1\$s",
    "entries_count" to "entradas",
    "table_header_recent" to "Recente",
    "table_header_open" to "Abrir"
)

object LocalizationManager {
    fun getString(stringId: String, language: String): String {
        val map = when (language) {
            "pt-BR" -> portugueseStrings
            else -> englishStrings
        }
        return map[stringId] ?: stringId
    }
}

// CompositionLocal for providing the current language
val LocalLanguage = compositionLocalOf { "en" }

@Composable
fun rememberLocalizedString(stringId: String): String {
    val language = LocalLanguage.current
    return LocalizationManager.getString(stringId, language)
}
